apiVersion: v1
kind: Service
metadata:
  name: shopware-service-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  ports:
    - port: 80
      protocol: TCP
      name: web
      targetPort: 80
  selector:
    app: shopware-{{ .Release.Name }}
    tier: frontend-{{ .Release.Name }}
  type: NodePort
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tls-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.shopware_url  }}`)
      kind: Rule
      priority: 1
      services:
        - name: shopware-service-{{ .Release.Name }}
          port: 80
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.shopware_url  }}`)
      kind: Rule
      priority: 1
      middlewares:
        - name: redirect-https-{{ .Release.Name }}
      services:
        - name: shopware-service-{{ .Release.Name }}
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopware-{{ .Release.Name }}
  labels:
    app: shopware-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  selector:
    matchLabels:
      app: shopware-{{ .Release.Name }}
      tier: frontend-{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shopware-{{ .Release.Name }}
        tier: frontend-{{ .Release.Name }}
        cd-hipay: cron-delete
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
      - image: {{ .Values.shopware_image }}:{{ .Values.shopware_tag }}
        imagePullPolicy: Always
        name: shopware-{{ .Release.Name }}
        resources:
          requests:
            memory: "3Gi"
            cpu: "750m"
            ephemeral-storage: "2Gi"
        envFrom:
          - configMapRef:
              name: shopware-configmap-{{ .Release.Name }}
        ports:
          - containerPort: 80
            name: shopware
        readinessProbe:
          httpGet:
            path: /
            port: shopware
            httpHeaders:
              - name: Host
                value: {{ .Values.shopware_url | quote }}
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: {{ .Values.shopware_url | quote }}
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 25
          timeoutSeconds: 10
        volumeMounts:
          - name: shopware-framework-config
            mountPath: /var/www/html/config/packages/framework.yaml
            subPath: framework.yaml
            readOnly: true
      volumes:
        - name: shopware-framework-config
          configMap:
            name: shopware-configmap-{{ .Release.Name }}
